Allow Black to handle string quote formatting
DigitalSlideArchive/ImageDePHI pull request #10
Opened 2022-12-09 21:54 UTC by brianhelba

This has several benefits:
* String quotes are now auto-formatted correctly; no need to fix quote-related Flake8 errors by hand.
  * Continue to type the quotes however you want. Black will just fix them afterwards.
* We can unpin Flake8.

Note the addition of `.git-blame-ignore-revs`, to avoid `git blame` attribution of these automated changes. See https://github.blog/changelog/2022-03-24-ignore-commits-in-the-blame-view-beta/ and [run `git config --global blame.ignoreRevsFile .git-blame-ignore-revs` locally if you want automatic support](https://michaelheap.com/git-ignore-rev/).

2022-12-12 17:42 UTC, naglepuff requested changes
I like the idea of making developers' lives easier. Can we make this auto-format to single quotes? Other projects in the Digital Slide Archive I've worked on all tend to use single quotes.

2022-12-12 18:01 UTC, Leengit commented
There are no doubt lots of opinions on this.  I am in favor of using all `black` defaults except the command line `--skip-magic-trailing-comma` (aka `-C`).  This promotes all Python code having the same look and feel even outside DigitalSlideArchive.  In the name of sacrificing for uniformity, this means a line length of 88, which I would otherwise consider too short.

Details: the `-C` tells `black` to treat
```python
a = [b, c]
```
and
```python
a = [b,
     c,]
```
the same, which is to put it all on one line if possible within 88 characters; otherwise one  list element per line.  Without `-C` the behavior is to choose one line if there is no comma after the last element (and it fits into 88 characters), and to choose one list element per line if there is a comma there.  (In particular, using `-C` doesn't deviate from the look of other repositories that don't use it because a call to `black` after `black -C` won't change anything.)

2022-12-12 18:10 UTC, jcfr commented
For new project, I suggest to standardize on double quotes and maximize use of existing tooling [^3].

[^3]: https://github.com/scikit-build/scikit-build/blob/359bb6ce59506b6527121fbea5ff3e4c8eb05396/.pre-commit-config.yaml#L35-L46

The use of `.git-blame-ignore-revs` [^1] helps to ensure `blame` works as expected both locally and with the GitHub UI.

To understand the rational behind the standardization, you may also be interested in discussion we had in the context of scikit-build [^2]

[^1]: https://github.com/Slicer/Slicer/pull/6306
[^2]: https://github.com/scikit-build/scikit-build/pull/665#issuecomment-1039573165

2022-12-12 19:17 UTC, brianhelba commented
Black is intentionally not configurable to use single quotes. See: https://github.com/psf/black/issues/118#issuecomment-380171356

The only alternate is the status quo, where we don't use Black to format quotes and force developers to fix things by hand.

2022-12-12 19:23 UTC, manthey commented
Black isn't the only auto-formatter.  autopep8 has been around for a decade, whereas black only came out of beta a year ago.

2022-12-13 16:00 UTC, naglepuff approved these changes
Sure, let's go for it. I'm fine following black's decision, so we can move on to more useful development.

2022-12-13 18:05 UTC, merged