Add setup.py
DigitalSlideArchive/ImageDePHI pull request #15
Opened 2022-12-12 19:16 UTC by naglepuff

2022-12-12 19:56 UTC, jcfr commented
For new package, I suggest to provide a `pyproject.toml` [^1] instead of legacy `setup.py`.

[^1]: https://pip.pypa.io/en/stable/reference/build-system/

2022-12-13 14:20 UTC, brianhelba commented on setup.py
> +    name='Image DePHI',
```suggestion
    name='ImageDePHI',
```
This shouldn't have spaces, since it's used to build the package file name.

2022-12-13 14:21 UTC, brianhelba requested changes
A change to the package name is needed.

2022-12-13 15:07 UTC, brianhelba commented
We can discuss `pyproject.toml` in #21. I think this PR is fine using the legacy mechanism.

2022-12-13 17:49 UTC, brianhelba approved these changes

2022-12-13 17:49 UTC, merged